### ISSUE TITLE
LipikaBoard on iPhone 12 - not able to type ಶ (sha)

### ISSUE THREAD

**Issue by ssnkumar** [ratreya/lipika-board#5]
When I try to type sha, it comes as ಸ್ಹ instead of ಶ.
But, Sha gets transliterated as ಷ.
Please let me know, how to get ಶ in Lipika-Board keyboard on iPhone-12.

**Comment by ratreya** [comment]
I think you are using Ksharana Input Scheme. For Kannada, please change to Baraha or Barahavat as they are better suited. This particular bug with Ksharana has been fixed in LipikaIME and will be ported over to LipikaBoard soon. Thanks!

**Comment by ssnkumar** [comment]
in iPhone 12, when I install and use LipikaBoard, it doesn't provide an option to select the transliteration scheme. So, whatever default scheme was provided is being used, I haven't changed the scheme.

**Comment by ratreya** [comment]
Please open LipikaApp on your phone and make the selection.

**Comment by ssnkumar** [comment]
Thank you very much.
