### ISSUE TITLE
How to type rank using Kannada font on LipikaIME on Macbook Pro

### ISSUE THREAD

**Issue by ssnkumar** [ratreya/lipika-board#7]
I know that, ^ is the Zero-Width-Non-Joiner on Macbook (LipikaIME).
For writing Rank in Kannada, I should type r^yAMk.
When I type this in the URL box of browser, it gets the word correctly.
But, when I type the same in Winword, it gets it wrong.
Even in this text box, it gets it wrong and here is what I am getting: ರ‌್ಯಾಂಕ್
So, want to know, how to get this correctly on Macbook Pro?

**Comment by ratreya** [comment]
Type r^^yAMk and you should get ರ್‍ಯಂಕ್.

**Comment by ssnkumar** [comment]
Tried it. That works. Thank you very much for the superfast response.
